@echo off
echo Checking for virtual environment...

if not exist venv (
    echo Virtual environment not found. Running setup...
    call setup_env.bat
) else (
    echo Activating virtual environment...
    call venv\Scripts\activate.bat
    
    echo Installing/updating dependencies...
    pip install -r requirements.txt
)

echo Starting the application...
python app.py
